### ISSUE TITLE
Results out of range 0x20000000000:0x3fffffffffffff

### ISSUE THREAD

**Issue by mehdibil** [unclevito2017/Quantum-mining-puzzle-66#3]
hello, the results given are out of the range for example : 0x4000000,0x17dc00000000,0x4db700000000...... if you cen give me your email i will send you a csv with all results jobs, thank you

**Comment by unclevito2017** [comment]
I appreciate your input but they are not the results if you are using the simulator it does not solve he puzzle it just verifies the code. what you are looking at are system calculations not the final result.  If you are using the live kyoto resource 10 minutes is not enough time to solve 66. Even though this is a quantum computer it is not of the speed that people might think.  Todays quantum computers may be faster than home computers for some calculations but they are not at the seed if light yet; So for example using a home computer for 66 36893488147419103232 almost 37 quintillion points at 1 billion per second would take 1,189,153 years so possibly with todays quantum computers as a guess 1 year and again that is a guess because they are not rated at speed/second. The software has been updated but when  someone actually solves 66 the result will appear in the user's command screen as found. The main reason for posting this code  is to get more people involved and to refine code so when the quantum computers get faster and the priced decreases we will be ready for that eventuality

**Comment by mehdibil** [comment]
thank you for your answer, waiting for a new script who can solve puzzle with quantum.
